# Generated by Django 5.0.3 on 2024-03-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0002_initial"),
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="likes.like"
            ),
        ),
    ]
