# Generated by Django 5.0.3 on 2024-03-19 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("liked_by", "comment_id")},
        ),
    ]
