# Generated by Django 5.0.3 on 2024-03-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="comment_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="like",
            name="post_id",
            field=models.IntegerField(default=0),
        ),
    ]
