# Generated by Django 5.0.3 on 2024-03-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0005_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
    ]
